# Generated by Django 5.0.1 on 2024-01-18 16:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_type', models.CharField(max_length=10)),
                ('registration', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperationalFPL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ofp_format', models.CharField(choices=[('0H', '0H'), ('OX', 'OX'), ('ForeFlight', 'ForeFlight')], max_length=10)),
                ('ofp', models.FileField(blank=True, upload_to='ofps/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='PDF OFP PLEASE!')])),
            ],
        ),
        migrations.CreateModel(
            name='Fax_elts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captain', models.CharField(max_length=50)),
                ('fir_countries', models.TextField(verbose_name='Overflown Countries Separated by Comma ",":')),
                ('fir_points', models.TextField(verbose_name='FIR points Separated by Comma ",":')),
                ('generated', models.DateTimeField(default=django.utils.timezone.now)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.aircraft')),
                ('generated_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core_app.operationalfpl')),
            ],
        ),
    ]
