# Generated by Django 5.0.1 on 2024-01-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_operationalfpl_ofp_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationalfpl',
            name='ofp',
            field=models.FileField(blank=True, upload_to='ofps/'),
        ),
    ]
