# Generated by Django 5.0.1 on 2024-01-18 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_alter_operationalfpl_ofp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationalfpl',
            name='ofp_name',
        ),
    ]
