# Generated by Django 5.0.1 on 2024-01-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_remove_operationalfpl_ofp_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fax_elts',
            name='fir_countries',
            field=models.TextField(verbose_name='Overflown Countries:'),
        ),
        migrations.AlterField(
            model_name='fax_elts',
            name='fir_points',
            field=models.TextField(verbose_name='FIR points:'),
        ),
        migrations.AlterField(
            model_name='operationalfpl',
            name='ofp',
            field=models.FileField(blank=True, upload_to='ofps/', verbose_name='Operation FPL'),
        ),
    ]
